import { Template } from '@/types'

export const SYSTEM_TEMPLATES: Omit<Template, 'id'>[] = [
  {
    name: 'Job Offer — Formal',
    reply_type: 'offer',
    tone: 'formal',
    prompt_snippet: 'Offer the role with salary and joining date details.',
    is_system: true,
  },
  {
    name: 'Job Offer — Hinglish',
    reply_type: 'offer',
    tone: 'hinglish',
    prompt_snippet: 'Offer the role in warm Hinglish, congratulate them.',
    is_system: true,
  },
  {
    name: 'Kind Rejection',
    reply_type: 'rejection',
    tone: 'friendly',
    prompt_snippet: 'Reject the candidate warmly, keep the door open for future roles.',
    is_system: true,
  },
  {
    name: 'Kind Rejection — Hinglish',
    reply_type: 'rejection',
    tone: 'hinglish',
    prompt_snippet: 'Reject kindly in Hinglish, maintain a positive tone.',
    is_system: true,
  },
  {
    name: 'Shortlisted — Formal',
    reply_type: 'shortlist',
    tone: 'formal',
    prompt_snippet: 'Inform them they have been shortlisted and what comes next.',
    is_system: true,
  },
  {
    name: 'Shortlisted — Hinglish',
    reply_type: 'shortlist',
    tone: 'hinglish',
    prompt_snippet: 'Share shortlist news in Hinglish with excitement.',
    is_system: true,
  },
  {
    name: 'Interview Invite — Formal',
    reply_type: 'interview_invite',
    tone: 'formal',
    prompt_snippet: 'Invite with date, time, venue/link, and interviewer name.',
    is_system: true,
  },
  {
    name: 'Interview Invite — Friendly',
    reply_type: 'interview_invite',
    tone: 'friendly',
    prompt_snippet: 'Casual interview invite with all details included.',
    is_system: true,
  },
  {
    name: 'Interview Invite — Hinglish',
    reply_type: 'interview_invite',
    tone: 'hinglish',
    prompt_snippet: 'Interview invite in Hinglish with date and time.',
    is_system: true,
  },
  {
    name: 'Reschedule — Formal',
    reply_type: 'reschedule',
    tone: 'formal',
    prompt_snippet: 'Apologize for the change and confirm new time.',
    is_system: true,
  },
  {
    name: 'Reschedule — Hinglish',
    reply_type: 'reschedule',
    tone: 'hinglish',
    prompt_snippet: 'Reschedule politely in Hinglish.',
    is_system: true,
  },
  {
    name: 'No Show Follow-up',
    reply_type: 'no_show',
    tone: 'friendly',
    prompt_snippet: 'Follow up after candidate missed the interview, ask if they want to reschedule.',
    is_system: true,
  },
  {
    name: 'No Show — Hinglish',
    reply_type: 'no_show',
    tone: 'hinglish',
    prompt_snippet: 'No-show follow-up in caring Hinglish.',
    is_system: true,
  },
  {
    name: 'General Follow-up',
    reply_type: 'follow_up',
    tone: 'friendly',
    prompt_snippet: 'Check in on candidate status or nudge for a response.',
    is_system: true,
  },
  {
    name: 'Follow-up — Hinglish',
    reply_type: 'follow_up',
    tone: 'hinglish',
    prompt_snippet: 'Friendly follow-up nudge in Hinglish.',
    is_system: true,
  },
  {
    name: 'Salary Negotiation',
    reply_type: 'salary_negotiation',
    tone: 'formal',
    prompt_snippet: 'Respond to salary counter-offer professionally.',
    is_system: true,
  },
  {
    name: 'Salary Negotiation — Friendly',
    reply_type: 'salary_negotiation',
    tone: 'friendly',
    prompt_snippet: 'Discuss salary with empathy and transparency.',
    is_system: true,
  },
  {
    name: 'Joining Confirmation',
    reply_type: 'joining_confirmation',
    tone: 'formal',
    prompt_snippet: 'Confirm joining date, time, documents needed.',
    is_system: true,
  },
  {
    name: 'Joining Confirmation — Hinglish',
    reply_type: 'joining_confirmation',
    tone: 'hinglish',
    prompt_snippet: 'Joining confirmation in warm Hinglish.',
    is_system: true,
  },
  {
    name: 'Post-Interview Thank You',
    reply_type: 'thank_you',
    tone: 'friendly',
    prompt_snippet: 'Thank candidate after interview and share expected timeline.',
    is_system: true,
  },
]
